name:                rublev
version:             0.1.0.0
github:              "githubuser/rublev"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rublev#readme>

build-tools:
- happy

dependencies:
- base==4.8.2.0
- linear
- vector
- OpenCL
- primitive
- mtl
- array
- deepseq
- MonadRandom
- JuicyPixels
- time
- CLUtil
- interpolate
- language-c-quote
- pango
- cairo
- OpenGL
# - glib==0.13.4.0
# - gtk2hs-buildtools
# - Cabal==1.24.2.0

library:
  source-dirs: src
  cc-options: -U__BLOCKS__ -D_Nonnull=
  cpp-options: -DCALLCONV=ccall -D__nullable= -D__nonnull=

executables:
  rublev-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rublev
    cc-options: -U__BLOCKS__ -D_Nonnull=
    cpp-options: -DCALLCONV=ccall -D__nullable= -D__Nonnull=

  rt:
    main:                Realtime.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rublev
    cc-options: -U__BLOCKS__ -D_Nonnull=
    cpp-options: -DCALLCONV=ccall -D__nullable= -D__Nonnull=

tests:
  rublev-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rublev
